import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Catch Server Rendering Error',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <header>
          <h1>Catch Server Rendering Error</h1>
          <p>
            Context: Catching server rendering error and showing fallback component without using error boundaries.
          </p>
          <p>
            The two server component has a 60% chance of throwing errors. Keep refreshing to reload them.
          </p>

          <a href="/" style={ { textDecoration: 'underline', color: '#aaa' } }>refresh page</a>
        </header>
        { children }
        <footer>
          <a href="https://github.com/alfonsusac/next-js-server-error-trycatch">source</a> - by Alfonsus Ardani
        </footer>
      </body>
    </html>
  )
}
